name = "paste-worker"
main = "src/index.js"
compatibility_date = "2025-04-24"

workers_dev = false

[[routes]]
pattern = "paste.pirdel.ir"
custom_domain = true

[[kv_namespaces]]
binding = "CLIPS"
id = "e5007944d8a54ec9878fad622f4fbc73"

[vars]
SITE_TITLE = "Pirdel Clipboard"
DEFAULT_TTL = "600"
MAX_TEXT_LENGTH = "50000"
ADMIN_PASSWORD = "MADmad320324"
